CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS tenant (
    uuid UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    document VARCHAR(100) NOT NULL UNIQUE,
    live BOOLEAN NOT NULL DEFAULT TRUE,
    create_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    update_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);
