definitions:
  dto.CreateTenantRequest:
    properties:
      document:
        type: string
      live:
        type: boolean
      name:
        type: string
    required:
    - document
    - live
    - name
    type: object
  dto.TenantResponse:
    properties:
      createAt:
        type: string
      document:
        type: string
      live:
        type: boolean
      name:
        type: string
      updateAt:
        type: string
      uuid:
        type: string
    type: object
  rest_err.Causes:
    properties:
      field:
        type: string
      message:
        type: string
    type: object
  rest_err.RestErr:
    properties:
      causes:
        items:
          $ref: '#/definitions/rest_err.Causes'
        type: array
      code:
        type: integer
      error:
        type: string
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/tenant:
    post:
      consumes:
      - application/json
      description: Registra um novo tenant (empresa/organização) no sistema.
      parameters:
      - description: Objeto do tenant que precisa ser criado.
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateTenantRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Tenant criado com sucesso.
          schema:
            $ref: '#/definitions/dto.TenantResponse'
        "400":
          description: Requisição inválida (corpo JSON mal formatado ou dados de entrada
            inválidos).
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "409":
          description: Conflito (o 'document' fornecido já está em uso).
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "500":
          description: Erro interno do servidor.
          schema:
            $ref: '#/definitions/rest_err.RestErr'
      summary: Cria um novo Tenant
      tags:
      - Tenant
swagger: "2.0"
